name: Update Profile Animation

on:
  push:
    branches:
      - main  # Run on push for branch "main"
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger from Actions

jobs:
  update-profile:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant write permissions to the workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
      
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated snake animation [GitHub Actions]"
          file_pattern: dist/snake.svg

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
